### ISSUE TITLE
Опечатка в названии поля

### ISSUE THREAD

**Issue by lavafrai** [Kislorod4ik/ClickableWallpapersOnPython#3]
Возможно так и задумано, однако хочу вас уведомить, что похоже, поле weight класса Main (определяется в строке 182) должно называться width так как хранит в себе ширину экрана, а weight переводится как вес, а не ширина :)
![image](https://user-images.githubusercontent.com/79652972/159734677-c6c8ac47-a844-4ab3-9e44-0c72f2b3cfbd.png)

**Comment by lavafrai** [comment]
А еще Воскресенье пишется через 1 С )
![image](https://user-images.githubusercontent.com/79652972/159754371-29516a36-8984-417e-aa1c-01039a2852c9.png)
(Уж простите что докапываюсь)

**Comment by Kislorod4ik** [comment]
Спасибо за поправки) 
Писал на ночь глядя, не заметил)
